/*
 * Cosmo Tech Plaform API
 *
 * Cosmo Tech Platform API
 *
 * The version of the OpenAPI document: 3.0.0-dev
 * Contact: platform@cosmotech.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Cosmotech.Api;
using Com.Cosmotech.Model;
using Com.Cosmotech.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Cosmotech.Test.Model
{
    /// <summary>
    ///  Class for testing DatasetConnector
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DatasetConnectorTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DatasetConnector
        //private DatasetConnector instance;

        public DatasetConnectorTests()
        {
            // TODO uncomment below to create an instance of DatasetConnector
            //instance = new DatasetConnector();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DatasetConnector
        /// </summary>
        [Fact]
        public void DatasetConnectorInstanceTest()
        {
            // TODO uncomment below to test "IsType" DatasetConnector
            //Assert.IsType<DatasetConnector>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property '_Version'
        /// </summary>
        [Fact]
        public void _VersionTest()
        {
            // TODO unit test for the property '_Version'
        }
        /// <summary>
        /// Test the property 'ParametersValues'
        /// </summary>
        [Fact]
        public void ParametersValuesTest()
        {
            // TODO unit test for the property 'ParametersValues'
        }

    }

}
