/*
 * Cosmo Tech Platform API
 *
 * Cosmo Tech Platform API
 *
 * The version of the OpenAPI document: 4.0.1-onprem
 * Contact: platform@cosmotech.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Cosmotech.Model;
using Com.Cosmotech.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Cosmotech.Test.Model
{
    /// <summary>
    ///  Class for testing OrganizationSecurity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrganizationSecurityTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrganizationSecurity
        //private OrganizationSecurity instance;

        public OrganizationSecurityTests()
        {
            // TODO uncomment below to create an instance of OrganizationSecurity
            //instance = new OrganizationSecurity();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrganizationSecurity
        /// </summary>
        [Fact]
        public void OrganizationSecurityInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrganizationSecurity
            //Assert.IsType<OrganizationSecurity>(instance);
        }

        /// <summary>
        /// Test the property 'VarDefault'
        /// </summary>
        [Fact]
        public void VarDefaultTest()
        {
            // TODO unit test for the property 'VarDefault'
        }

        /// <summary>
        /// Test the property 'AccessControlList'
        /// </summary>
        [Fact]
        public void AccessControlListTest()
        {
            // TODO unit test for the property 'AccessControlList'
        }
    }
}
