/*
 * Cosmo Tech Platform API
 *
 * Cosmo Tech Platform API
 *
 * The version of the OpenAPI document: 3.2.2-SNAPSHOT
 * Contact: platform@cosmotech.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Cosmotech.Model;
using Com.Cosmotech.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Cosmotech.Test.Model
{
    /// <summary>
    ///  Class for testing RunSearch
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RunSearchTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RunSearch
        //private RunSearch instance;

        public RunSearchTests()
        {
            // TODO uncomment below to create an instance of RunSearch
            //instance = new RunSearch();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RunSearch
        /// </summary>
        [Fact]
        public void RunSearchInstanceTest()
        {
            // TODO uncomment below to test "IsType" RunSearch
            //Assert.IsType<RunSearch>(instance);
        }

        /// <summary>
        /// Test the property 'SolutionId'
        /// </summary>
        [Fact]
        public void SolutionIdTest()
        {
            // TODO unit test for the property 'SolutionId'
        }

        /// <summary>
        /// Test the property 'RunTemplateId'
        /// </summary>
        [Fact]
        public void RunTemplateIdTest()
        {
            // TODO unit test for the property 'RunTemplateId'
        }

        /// <summary>
        /// Test the property 'WorkspaceId'
        /// </summary>
        [Fact]
        public void WorkspaceIdTest()
        {
            // TODO unit test for the property 'WorkspaceId'
        }

        /// <summary>
        /// Test the property 'RunnerId'
        /// </summary>
        [Fact]
        public void RunnerIdTest()
        {
            // TODO unit test for the property 'RunnerId'
        }

        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

        /// <summary>
        /// Test the property 'WorkflowId'
        /// </summary>
        [Fact]
        public void WorkflowIdTest()
        {
            // TODO unit test for the property 'WorkflowId'
        }

        /// <summary>
        /// Test the property 'WorkflowName'
        /// </summary>
        [Fact]
        public void WorkflowNameTest()
        {
            // TODO unit test for the property 'WorkflowName'
        }

        /// <summary>
        /// Test the property 'OwnerId'
        /// </summary>
        [Fact]
        public void OwnerIdTest()
        {
            // TODO unit test for the property 'OwnerId'
        }
    }
}
