/*
 * Cosmo Tech Plaform API
 *
 * Cosmo Tech Platform API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Cosmotech.Api;
using Com.Cosmotech.Model;
using Com.Cosmotech.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Cosmotech.Test.Model
{
    /// <summary>
    ///  Class for testing ScenarioRunAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ScenarioRunAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ScenarioRunAllOf
        //private ScenarioRunAllOf instance;

        public ScenarioRunAllOfTests()
        {
            // TODO uncomment below to create an instance of ScenarioRunAllOf
            //instance = new ScenarioRunAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ScenarioRunAllOf
        /// </summary>
        [Fact]
        public void ScenarioRunAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsType" ScenarioRunAllOf
            //Assert.IsType<ScenarioRunAllOf>(instance);
        }


        /// <summary>
        /// Test the property 'DatasetList'
        /// </summary>
        [Fact]
        public void DatasetListTest()
        {
            // TODO unit test for the property 'DatasetList'
        }
        /// <summary>
        /// Test the property 'ParametersValues'
        /// </summary>
        [Fact]
        public void ParametersValuesTest()
        {
            // TODO unit test for the property 'ParametersValues'
        }
        /// <summary>
        /// Test the property 'SendInputToDataWarehouse'
        /// </summary>
        [Fact]
        public void SendInputToDataWarehouseTest()
        {
            // TODO unit test for the property 'SendInputToDataWarehouse'
        }
        /// <summary>
        /// Test the property 'DataWarehouseDB'
        /// </summary>
        [Fact]
        public void DataWarehouseDBTest()
        {
            // TODO unit test for the property 'DataWarehouseDB'
        }
        /// <summary>
        /// Test the property 'ResultsEventBusResourceUri'
        /// </summary>
        [Fact]
        public void ResultsEventBusResourceUriTest()
        {
            // TODO unit test for the property 'ResultsEventBusResourceUri'
        }
        /// <summary>
        /// Test the property 'ScenariorunEventBusResourceUri'
        /// </summary>
        [Fact]
        public void ScenariorunEventBusResourceUriTest()
        {
            // TODO unit test for the property 'ScenariorunEventBusResourceUri'
        }
        /// <summary>
        /// Test the property 'NodeLabel'
        /// </summary>
        [Fact]
        public void NodeLabelTest()
        {
            // TODO unit test for the property 'NodeLabel'
        }
        /// <summary>
        /// Test the property 'InitContainers'
        /// </summary>
        [Fact]
        public void InitContainersTest()
        {
            // TODO unit test for the property 'InitContainers'
        }
        /// <summary>
        /// Test the property 'MainContainer'
        /// </summary>
        [Fact]
        public void MainContainerTest()
        {
            // TODO unit test for the property 'MainContainer'
        }

    }

}
