/*
 * Cosmo Tech Plaform API
 *
 * Cosmo Tech Platform API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Cosmotech.Api;
using Com.Cosmotech.Model;
using Com.Cosmotech.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Cosmotech.Test.Model
{
    /// <summary>
    ///  Class for testing SimulationSearch
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SimulationSearchTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SimulationSearch
        //private SimulationSearch instance;

        public SimulationSearchTests()
        {
            // TODO uncomment below to create an instance of SimulationSearch
            //instance = new SimulationSearch();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SimulationSearch
        /// </summary>
        [Fact]
        public void SimulationSearchInstanceTest()
        {
            // TODO uncomment below to test "IsType" SimulationSearch
            //Assert.IsType<SimulationSearch>(instance);
        }


        /// <summary>
        /// Test the property 'SimulatorId'
        /// </summary>
        [Fact]
        public void SimulatorIdTest()
        {
            // TODO unit test for the property 'SimulatorId'
        }
        /// <summary>
        /// Test the property 'SimulatorAnalysisId'
        /// </summary>
        [Fact]
        public void SimulatorAnalysisIdTest()
        {
            // TODO unit test for the property 'SimulatorAnalysisId'
        }
        /// <summary>
        /// Test the property 'WorkspaceId'
        /// </summary>
        [Fact]
        public void WorkspaceIdTest()
        {
            // TODO unit test for the property 'WorkspaceId'
        }
        /// <summary>
        /// Test the property 'ScenarioId'
        /// </summary>
        [Fact]
        public void ScenarioIdTest()
        {
            // TODO unit test for the property 'ScenarioId'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'JobId'
        /// </summary>
        [Fact]
        public void JobIdTest()
        {
            // TODO unit test for the property 'JobId'
        }
        /// <summary>
        /// Test the property 'OwnerId'
        /// </summary>
        [Fact]
        public void OwnerIdTest()
        {
            // TODO unit test for the property 'OwnerId'
        }

    }

}
