/*
 * Cosmo Tech Plaform API
 *
 * Cosmo Tech Platform API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Cosmotech.Api;
using Com.Cosmotech.Model;
using Com.Cosmotech.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Cosmotech.Test.Model
{
    /// <summary>
    ///  Class for testing SimulationStartScenario
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SimulationStartScenarioTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SimulationStartScenario
        //private SimulationStartScenario instance;

        public SimulationStartScenarioTests()
        {
            // TODO uncomment below to create an instance of SimulationStartScenario
            //instance = new SimulationStartScenario();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SimulationStartScenario
        /// </summary>
        [Fact]
        public void SimulationStartScenarioInstanceTest()
        {
            // TODO uncomment below to test "IsType" SimulationStartScenario
            //Assert.IsType<SimulationStartScenario>(instance);
        }


        /// <summary>
        /// Test the property 'WorkspaceId'
        /// </summary>
        [Fact]
        public void WorkspaceIdTest()
        {
            // TODO unit test for the property 'WorkspaceId'
        }
        /// <summary>
        /// Test the property 'ScenarioId'
        /// </summary>
        [Fact]
        public void ScenarioIdTest()
        {
            // TODO unit test for the property 'ScenarioId'
        }

    }

}
