/*
 * Cosmo Tech Platform API
 *
 * Cosmo Tech Platform API
 *
 * The version of the OpenAPI document: 3.0.14-SNAPSHOT
 * Contact: platform@cosmotech.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Cosmotech.Api;
using Com.Cosmotech.Model;
using Com.Cosmotech.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Cosmotech.Test.Model
{
    /// <summary>
    ///  Class for testing TwinGraphHash
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TwinGraphHashTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TwinGraphHash
        //private TwinGraphHash instance;

        public TwinGraphHashTests()
        {
            // TODO uncomment below to create an instance of TwinGraphHash
            //instance = new TwinGraphHash();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TwinGraphHash
        /// </summary>
        [Fact]
        public void TwinGraphHashInstanceTest()
        {
            // TODO uncomment below to test "IsType" TwinGraphHash
            //Assert.IsType<TwinGraphHash>(instance);
        }


        /// <summary>
        /// Test the property 'Hash'
        /// </summary>
        [Fact]
        public void HashTest()
        {
            // TODO unit test for the property 'Hash'
        }

    }

}
