/*
 * Cosmo Tech Platform API
 *
 * Cosmo Tech Platform API
 *
 * The version of the OpenAPI document: 2.3.9
 * Contact: platform@cosmotech.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Cosmotech.Api;
using Com.Cosmotech.Model;
using Com.Cosmotech.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Cosmotech.Test.Model
{
    /// <summary>
    ///  Class for testing WorkspaceWebApp
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WorkspaceWebAppTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WorkspaceWebApp
        //private WorkspaceWebApp instance;

        public WorkspaceWebAppTests()
        {
            // TODO uncomment below to create an instance of WorkspaceWebApp
            //instance = new WorkspaceWebApp();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WorkspaceWebApp
        /// </summary>
        [Fact]
        public void WorkspaceWebAppInstanceTest()
        {
            // TODO uncomment below to test "IsType" WorkspaceWebApp
            //Assert.IsType<WorkspaceWebApp>(instance);
        }


        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'Iframes'
        /// </summary>
        [Fact]
        public void IframesTest()
        {
            // TODO unit test for the property 'Iframes'
        }
        /// <summary>
        /// Test the property 'Options'
        /// </summary>
        [Fact]
        public void OptionsTest()
        {
            // TODO unit test for the property 'Options'
        }

    }

}
