/*
 * Cosmo Tech Plaform API
 *
 * Cosmo Tech Platform API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Com.Cosmotech.Client.OpenAPIDateConverter;

namespace Com.Cosmotech.Model
{
    /// <summary>
    /// a Cloud Service resource
    /// </summary>
    [DataContract(Name = "PlatformService")]
    public partial class PlatformService : IEquatable<PlatformService>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PlatformService" /> class.
        /// </summary>
        /// <param name="resourceUri">the workspace specific uri for this service resource.</param>
        /// <param name="credentials">a freeform credentials object. Structure depends on service.</param>
        /// <param name="options">the service specific options.</param>
        public PlatformService(string resourceUri = default(string), Dictionary<string, Object> credentials = default(Dictionary<string, Object>), Dictionary<string, Object> options = default(Dictionary<string, Object>))
        {
            this.ResourceUri = resourceUri;
            this.Credentials = credentials;
            this.Options = options;
        }

        /// <summary>
        /// the cloud service name
        /// </summary>
        /// <value>the cloud service name</value>
        [DataMember(Name = "cloudService", EmitDefaultValue = false)]
        public string CloudService { get; private set; }

        /// <summary>
        /// Returns false as CloudService should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeCloudService()
        {
            return false;
        }

        /// <summary>
        /// the platform base uri for this service
        /// </summary>
        /// <value>the platform base uri for this service</value>
        [DataMember(Name = "baseUri", EmitDefaultValue = false)]
        public string BaseUri { get; private set; }

        /// <summary>
        /// Returns false as BaseUri should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeBaseUri()
        {
            return false;
        }

        /// <summary>
        /// the workspace specific uri for this service resource
        /// </summary>
        /// <value>the workspace specific uri for this service resource</value>
        [DataMember(Name = "resourceUri", EmitDefaultValue = false)]
        public string ResourceUri { get; set; }

        /// <summary>
        /// a freeform credentials object. Structure depends on service
        /// </summary>
        /// <value>a freeform credentials object. Structure depends on service</value>
        [DataMember(Name = "credentials", EmitDefaultValue = false)]
        public Dictionary<string, Object> Credentials { get; set; }

        /// <summary>
        /// the service specific options
        /// </summary>
        /// <value>the service specific options</value>
        [DataMember(Name = "options", EmitDefaultValue = false)]
        public Dictionary<string, Object> Options { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PlatformService {\n");
            sb.Append("  CloudService: ").Append(CloudService).Append("\n");
            sb.Append("  BaseUri: ").Append(BaseUri).Append("\n");
            sb.Append("  ResourceUri: ").Append(ResourceUri).Append("\n");
            sb.Append("  Credentials: ").Append(Credentials).Append("\n");
            sb.Append("  Options: ").Append(Options).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PlatformService);
        }

        /// <summary>
        /// Returns true if PlatformService instances are equal
        /// </summary>
        /// <param name="input">Instance of PlatformService to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PlatformService input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CloudService == input.CloudService ||
                    (this.CloudService != null &&
                    this.CloudService.Equals(input.CloudService))
                ) && 
                (
                    this.BaseUri == input.BaseUri ||
                    (this.BaseUri != null &&
                    this.BaseUri.Equals(input.BaseUri))
                ) && 
                (
                    this.ResourceUri == input.ResourceUri ||
                    (this.ResourceUri != null &&
                    this.ResourceUri.Equals(input.ResourceUri))
                ) && 
                (
                    this.Credentials == input.Credentials ||
                    this.Credentials != null &&
                    input.Credentials != null &&
                    this.Credentials.SequenceEqual(input.Credentials)
                ) && 
                (
                    this.Options == input.Options ||
                    this.Options != null &&
                    input.Options != null &&
                    this.Options.SequenceEqual(input.Options)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CloudService != null)
                    hashCode = hashCode * 59 + this.CloudService.GetHashCode();
                if (this.BaseUri != null)
                    hashCode = hashCode * 59 + this.BaseUri.GetHashCode();
                if (this.ResourceUri != null)
                    hashCode = hashCode * 59 + this.ResourceUri.GetHashCode();
                if (this.Credentials != null)
                    hashCode = hashCode * 59 + this.Credentials.GetHashCode();
                if (this.Options != null)
                    hashCode = hashCode * 59 + this.Options.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
