/*
 * Cosmo Tech Plaform API
 *
 * Cosmo Tech Platform API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Com.Cosmotech.Client.OpenAPIDateConverter;

namespace Com.Cosmotech.Model
{
    /// <summary>
    /// a previously ran or running Scenario Analysis with run information
    /// </summary>
    [DataContract(Name = "ScenarioRunAnalysis_allOf")]
    public partial class ScenarioRunAnalysisAllOf : IEquatable<ScenarioRunAnalysisAllOf>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ScenarioRunAnalysisAllOf" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        public ScenarioRunAnalysisAllOf()
        {
        }

        /// <summary>
        /// the Simulation Run Id
        /// </summary>
        /// <value>the Simulation Run Id</value>
        [DataMember(Name = "simulationId", EmitDefaultValue = false)]
        public string SimulationId { get; private set; }

        /// <summary>
        /// Returns false as SimulationId should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeSimulationId()
        {
            return false;
        }

        /// <summary>
        /// the Simulation Run State
        /// </summary>
        /// <value>the Simulation Run State</value>
        [DataMember(Name = "simulationState", EmitDefaultValue = false)]
        public string SimulationState { get; private set; }

        /// <summary>
        /// Returns false as SimulationState should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeSimulationState()
        {
            return false;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ScenarioRunAnalysisAllOf {\n");
            sb.Append("  SimulationId: ").Append(SimulationId).Append("\n");
            sb.Append("  SimulationState: ").Append(SimulationState).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ScenarioRunAnalysisAllOf);
        }

        /// <summary>
        /// Returns true if ScenarioRunAnalysisAllOf instances are equal
        /// </summary>
        /// <param name="input">Instance of ScenarioRunAnalysisAllOf to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ScenarioRunAnalysisAllOf input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.SimulationId == input.SimulationId ||
                    (this.SimulationId != null &&
                    this.SimulationId.Equals(input.SimulationId))
                ) && 
                (
                    this.SimulationState == input.SimulationState ||
                    (this.SimulationState != null &&
                    this.SimulationState.Equals(input.SimulationState))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.SimulationId != null)
                    hashCode = hashCode * 59 + this.SimulationId.GetHashCode();
                if (this.SimulationState != null)
                    hashCode = hashCode * 59 + this.SimulationState.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
