/*
 * Cosmo Tech Plaform API
 *
 * Cosmo Tech Platform API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Com.Cosmotech.Client.OpenAPIDateConverter;

namespace Com.Cosmotech.Model
{
    /// <summary>
    /// the parameters to run directly a Solution
    /// </summary>
    [DataContract(Name = "ScenarioRunStartSolution")]
    public partial class ScenarioRunStartSolution : IEquatable<ScenarioRunStartSolution>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ScenarioRunStartSolution" /> class.
        /// </summary>
        /// <param name="solutionId">the Solution Id.</param>
        /// <param name="runTemplateId">the Solution Run Template id.</param>
        /// <param name="datasetList">the list of Dataset Id associated to this Analysis.</param>
        /// <param name="parametersValues">the list of Solution Run Template parameters values.</param>
        /// <param name="sendInputToDataWarehouse">whether or not the Dataset values and the input parameters values are send to the DataWarehouse prior to ScenarioRun Run.</param>
        /// <param name="dataWarehouseDB">the DataWarehouse database name to send data if sendInputToDataWarehouse is set.</param>
        /// <param name="resultsEventBusResourceUri">the event bus which receive Workspace ScenarioRun results messages. Message won&#39;t be send if this is not set.</param>
        /// <param name="scenariorunEventBusResourceUri">the event bus which receive Workspace ScenarioRun events messages. Message won&#39;t be send if this is not set.</param>
        public ScenarioRunStartSolution(string solutionId = default(string), string runTemplateId = default(string), List<string> datasetList = default(List<string>), List<RunTemplateParameterValue> parametersValues = default(List<RunTemplateParameterValue>), bool sendInputToDataWarehouse = default(bool), string dataWarehouseDB = default(string), string resultsEventBusResourceUri = default(string), string scenariorunEventBusResourceUri = default(string))
        {
            this.SolutionId = solutionId;
            this.RunTemplateId = runTemplateId;
            this.DatasetList = datasetList;
            this.ParametersValues = parametersValues;
            this.SendInputToDataWarehouse = sendInputToDataWarehouse;
            this.DataWarehouseDB = dataWarehouseDB;
            this.ResultsEventBusResourceUri = resultsEventBusResourceUri;
            this.ScenariorunEventBusResourceUri = scenariorunEventBusResourceUri;
        }

        /// <summary>
        /// the Solution Id
        /// </summary>
        /// <value>the Solution Id</value>
        [DataMember(Name = "solutionId", EmitDefaultValue = false)]
        public string SolutionId { get; set; }

        /// <summary>
        /// the Solution Run Template id
        /// </summary>
        /// <value>the Solution Run Template id</value>
        [DataMember(Name = "runTemplateId", EmitDefaultValue = false)]
        public string RunTemplateId { get; set; }

        /// <summary>
        /// the list of Dataset Id associated to this Analysis
        /// </summary>
        /// <value>the list of Dataset Id associated to this Analysis</value>
        [DataMember(Name = "datasetList", EmitDefaultValue = false)]
        public List<string> DatasetList { get; set; }

        /// <summary>
        /// the list of Solution Run Template parameters values
        /// </summary>
        /// <value>the list of Solution Run Template parameters values</value>
        [DataMember(Name = "parametersValues", EmitDefaultValue = false)]
        public List<RunTemplateParameterValue> ParametersValues { get; set; }

        /// <summary>
        /// whether or not the Dataset values and the input parameters values are send to the DataWarehouse prior to ScenarioRun Run
        /// </summary>
        /// <value>whether or not the Dataset values and the input parameters values are send to the DataWarehouse prior to ScenarioRun Run</value>
        [DataMember(Name = "sendInputToDataWarehouse", EmitDefaultValue = false)]
        public bool SendInputToDataWarehouse { get; set; }

        /// <summary>
        /// the DataWarehouse database name to send data if sendInputToDataWarehouse is set
        /// </summary>
        /// <value>the DataWarehouse database name to send data if sendInputToDataWarehouse is set</value>
        [DataMember(Name = "dataWarehouseDB", EmitDefaultValue = false)]
        public string DataWarehouseDB { get; set; }

        /// <summary>
        /// the event bus which receive Workspace ScenarioRun results messages. Message won&#39;t be send if this is not set
        /// </summary>
        /// <value>the event bus which receive Workspace ScenarioRun results messages. Message won&#39;t be send if this is not set</value>
        [DataMember(Name = "resultsEventBusResourceUri", EmitDefaultValue = false)]
        public string ResultsEventBusResourceUri { get; set; }

        /// <summary>
        /// the event bus which receive Workspace ScenarioRun events messages. Message won&#39;t be send if this is not set
        /// </summary>
        /// <value>the event bus which receive Workspace ScenarioRun events messages. Message won&#39;t be send if this is not set</value>
        [DataMember(Name = "scenariorunEventBusResourceUri", EmitDefaultValue = false)]
        public string ScenariorunEventBusResourceUri { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ScenarioRunStartSolution {\n");
            sb.Append("  SolutionId: ").Append(SolutionId).Append("\n");
            sb.Append("  RunTemplateId: ").Append(RunTemplateId).Append("\n");
            sb.Append("  DatasetList: ").Append(DatasetList).Append("\n");
            sb.Append("  ParametersValues: ").Append(ParametersValues).Append("\n");
            sb.Append("  SendInputToDataWarehouse: ").Append(SendInputToDataWarehouse).Append("\n");
            sb.Append("  DataWarehouseDB: ").Append(DataWarehouseDB).Append("\n");
            sb.Append("  ResultsEventBusResourceUri: ").Append(ResultsEventBusResourceUri).Append("\n");
            sb.Append("  ScenariorunEventBusResourceUri: ").Append(ScenariorunEventBusResourceUri).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ScenarioRunStartSolution);
        }

        /// <summary>
        /// Returns true if ScenarioRunStartSolution instances are equal
        /// </summary>
        /// <param name="input">Instance of ScenarioRunStartSolution to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ScenarioRunStartSolution input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.SolutionId == input.SolutionId ||
                    (this.SolutionId != null &&
                    this.SolutionId.Equals(input.SolutionId))
                ) && 
                (
                    this.RunTemplateId == input.RunTemplateId ||
                    (this.RunTemplateId != null &&
                    this.RunTemplateId.Equals(input.RunTemplateId))
                ) && 
                (
                    this.DatasetList == input.DatasetList ||
                    this.DatasetList != null &&
                    input.DatasetList != null &&
                    this.DatasetList.SequenceEqual(input.DatasetList)
                ) && 
                (
                    this.ParametersValues == input.ParametersValues ||
                    this.ParametersValues != null &&
                    input.ParametersValues != null &&
                    this.ParametersValues.SequenceEqual(input.ParametersValues)
                ) && 
                (
                    this.SendInputToDataWarehouse == input.SendInputToDataWarehouse ||
                    this.SendInputToDataWarehouse.Equals(input.SendInputToDataWarehouse)
                ) && 
                (
                    this.DataWarehouseDB == input.DataWarehouseDB ||
                    (this.DataWarehouseDB != null &&
                    this.DataWarehouseDB.Equals(input.DataWarehouseDB))
                ) && 
                (
                    this.ResultsEventBusResourceUri == input.ResultsEventBusResourceUri ||
                    (this.ResultsEventBusResourceUri != null &&
                    this.ResultsEventBusResourceUri.Equals(input.ResultsEventBusResourceUri))
                ) && 
                (
                    this.ScenariorunEventBusResourceUri == input.ScenariorunEventBusResourceUri ||
                    (this.ScenariorunEventBusResourceUri != null &&
                    this.ScenariorunEventBusResourceUri.Equals(input.ScenariorunEventBusResourceUri))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.SolutionId != null)
                    hashCode = hashCode * 59 + this.SolutionId.GetHashCode();
                if (this.RunTemplateId != null)
                    hashCode = hashCode * 59 + this.RunTemplateId.GetHashCode();
                if (this.DatasetList != null)
                    hashCode = hashCode * 59 + this.DatasetList.GetHashCode();
                if (this.ParametersValues != null)
                    hashCode = hashCode * 59 + this.ParametersValues.GetHashCode();
                hashCode = hashCode * 59 + this.SendInputToDataWarehouse.GetHashCode();
                if (this.DataWarehouseDB != null)
                    hashCode = hashCode * 59 + this.DataWarehouseDB.GetHashCode();
                if (this.ResultsEventBusResourceUri != null)
                    hashCode = hashCode * 59 + this.ResultsEventBusResourceUri.GetHashCode();
                if (this.ScenariorunEventBusResourceUri != null)
                    hashCode = hashCode * 59 + this.ScenariorunEventBusResourceUri.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
